# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4733e0645d8c83a3a5643fdabcff0fdc3dddd1a958ccf4b41d8e647dd8a3e125b9e1a286168ebd6c738830429d7634ba8e16ff4bfe221d9e8b01b8032146bac2

test:
  secret_key_base: c6910704b077fb22a9e45a7ae4a79eb8cd78bd09546ea7b1cf176fc5a64567657b44f92fef6cec05af2233b9f491f19f9680d42b13dc6e3e626508f146c6024c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
